const schedule = require('node-schedule');
const { getTrendingVideos, uploadToYouTube } = require('./youtube-api');
const { processVideo } = require('./processor');

let job = null;
let currentTokens = null;
let running = false;

async function runOnce(tokens) {
  if (running) {
    console.log('[Auto] Already running, skipping.');
    return { skipped: true };
  }
  running = true;

  const log = [];
  const addLog = msg => { console.log('[Auto]', msg); log.push(msg); };

  try {
    addLog('Fetching trending videos...');
    const videos = await getTrendingVideos({ maxResults: 5 });
    if (!videos.length) {
      addLog('No trending videos found.');
      return { success: false, log };
    }

    const video = videos[0];
    addLog(`Processing: "${video.title}"`);

    const clips = await processVideo(video.url, { autoDetect: true, clipDuration: 60 }, evt => {
      addLog(`${evt.step} (${evt.progress}%)`);
    });

    if (!clips.length) {
      addLog('No clips generated.');
      return { success: false, log };
    }

    const clip = clips[0];

    if (tokens) {
      addLog('Uploading to YouTube...');
      const result = await uploadToYouTube({
        clipPath: clip.clipPath,
        title: `${video.title.slice(0, 80)} - Highlights`,
        description: `Best moments from:\n${video.url}\n\nGenerated by ClipVault`,
        tags: ['Shorts', 'Trending', 'Highlights', 'ClipVault'],
        privacyStatus: 'public',
        tokens
      });
      addLog(`Uploaded → https://youtube.com/watch?v=${result.videoId}`);
    }

    return { success: true, log, clip };
  } catch (err) {
    addLog(`Error: ${err.message}`);
    return { success: false, error: err.message, log };
  } finally {
    running = false;
  }
}

function start(tokens, intervalHours = 24) {
  currentTokens = tokens;
  if (job) job.cancel();

  // Run immediately, then on schedule
  runOnce(tokens);

  const rule = new schedule.RecurrenceRule();
  rule.hour = new schedule.Range(0, 23, intervalHours);
  rule.minute = 0;

  job = schedule.scheduleJob(rule, () => runOnce(currentTokens));
  console.log(`[Auto] Scheduled every ${intervalHours}h`);
}

function stop() {
  if (job) { job.cancel(); job = null; }
  console.log('[Auto] Stopped');
}

function isActive() { return job !== null; }

module.exports = { start, stop, isActive, runOnce };
